### ISSUE TITLE
Provide package for the plugin center

### ISSUE THREAD

**Issue by markiewb** [Chris2011/netbeans-angular2-code-templates#1]
I am not a user of the plugin, but the installation procedure is too difficult. Provide a package with the code templates at the plugin center, so that the templates can be used by more users!

At https://github.com/markiewb/eclipsecodeformatter_for_netbeans/commit/f018cfc8b36adccf19240125e87b49056d6a64d3 you can see how to register the code template files in the layer.xml

**Comment by Chris2011** [comment]
Thx for the hint and the info, I will create one asap.

**Comment by markiewb** [comment]
@Chris2011: Any news here? IMO it should be easy to implement. The documentation, releasing and publishing should take longer than the implementation/configuration :)

**Comment by Chris2011** [comment]
@markiewb not yet, I know that it should be easy, but I didn't find time until now, so I will check it this week oder the week after. Thx for the interests :)

**Comment by Chris2011** [comment]
In the actual develop branch I created the plugin for this. I will build and deploy it soon to the plugin center of netbeans.

**Comment by markiewb** [comment]
Cool!

**Comment by Chris2011** [comment]
I published it, have to waiting for the approval.
