### ISSUE TITLE
ng2-ngSwitch

### ISSUE THREAD

**Issue by mariolenis** [Chris2011/netbeans-angular2-code-templates#2]
ng2-ngSwitch HTML template generates a wrong syntax to evaluate cases, it generates `ngSwitchWhen`, correct syntax is `ngSwitchCase`

**Comment by Chris2011** [comment]
Thx, I will have a look on this soon.

**Comment by Chris2011** [comment]
Here it is: https://github.com/Chris2011/netbeans-angular2-code-templates/releases/tag/1.0.1
I will publish it on the plugin center too.
