### ISSUE TITLE
does not work on netbeans 8.2

### ISSUE THREAD

**Issue by phil123456** [Chris2011/netbeans-angular2-code-templates#3]
Hi,

the snippet completion does not work at all

I tried TAB and CTRL+TAB , nothing shows up
I restarted the ide, same thing

no error on install, no notification whatsoever

Product Version: NetBeans IDE 8.2 (Build 201609300101)
Java: 1.8.0_112; Java HotSpot(TM) 64-Bit Server VM 25.112-b15
Runtime: Java(TM) SE Runtime Environment 1.8.0_112-b15
System: Windows 7 version 6.1 running on amd64; Cp1252; en_US (nb)

please help me fix this one
thanks

**Comment by Chris2011** [comment]
Please use licecap to create a little screen capture: http://www.cockos.com/licecap/

**Comment by phil123456** [comment]
http://i.imgur.com/VTVgT9B.png

pressing tab just adds a tab space

**Comment by Chris2011** [comment]
I only can guess with this less information, it is a .ts file right if yes, TypeScript has no code completion for code templates yet: https://github.com/Everlaw/nbts/issues/67

This is a known bug as you can see it inside my readme.

**Comment by phil123456** [comment]
but the whole ideo of that plugin is to provide snippet for angular right ? 
I dont get it

**Comment by Chris2011** [comment]
yes and the snippet work after hit TAB to expand the snippet to the code which is laying behind of e.g. ng2-switch. It provides NOT adding those templates to the code completion, because it should work out of the box for the giving language. For JS e.g. it works perfect, you can create custom templates and see it inside code completion. I created a ticket for this and someone fixed that. But TypeScript is a plugin too, which comes from someone else and they didn't implemented code completion for code templates yet as you can see my requested ticket so this is not my fault and I can't fix it in my plugin, because it is not part of my plugin.

**Comment by phil123456** [comment]
so your pluggin wont help so far, I thought it was a port of the angular snippet plugin for VIsual Studio Code

**Comment by Chris2011** [comment]
it is, but it will not provides code completion if the code completion is not available for some languages for code templates. In general code completion should work in each language, if it is implemented AND it should work for code templates/custom code templates (Which this plugin does, it will only provide code templates) are available in the language. If the nbts TypeScript plugin not allow showing code templates inside code completion, then it is so. You can use the code templates but you have to write the full name for this for example: ng2-ngSwitch -> TAB expand code.

**Comment by Chris2011** [comment]
ONLY the snippets are avaialable, it provides snippets for angular2 stuff in TS files and in HTML files, but not the code completion, this should work out of the box from the IDE.

**Comment by phil123456** [comment]
I tried ng2-ngSwitch then hit TAB, nothing appears

the code completion (CTRL+SPACE) works in .ts files

http://i.imgur.com/3pnaHSl.png

**Comment by Chris2011** [comment]
it is not about code completion it is about code templates INSIDE code completion, this is not working for TS file. Go to Options -> Editor -> Code Templates and switch to the language TypeScript and create a new, little custom test code template. If you expect to have this test code template inside the code completion, it is not there.

please have a look here: https://github.com/Chris2011/netbeans-angular2-code-templates

ng2-ngSwitch is only a template for HTML files. My fault, try for example: ng2-service inside a typescript file. It will appear after you hit TAB.

**Comment by Chris2011** [comment]
At the readme, if you read it full, everything is explained there.

**Comment by Chris2011** [comment]
@phil123456 please test the new release: https://github.com/Chris2011/netbeans-angular2-code-templates/releases/tag/1.0.2 it will fix the missing code templates for TS files.
